apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-press
  namespace: default
spec:
 chart:
   spec:
     chart: wordpress
     sourceRef:
       kind: HelmRepository
       name: bitnami
     version: ">=2.7.0"
 interval: 30m0s
