apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: net-data
  namespace: default
spec:
 chart:
   spec:
     chart: net-data
     sourceRef:
       kind: HelmRepository
       name: net-data
     version: ">=2.7.0"
 interval: 1m0s
