apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: default
spec:
 chart:
   spec:
     chart: netdata
     sourceRef:
       kind: HelmRepository
       name: netdata
     version: ">=2.7.0"
 interval: 1m0s
 values:
   parent:
   claiming:
     enabled: true
     token: LTQRyk26vZmK7sNH9LsHF4PMqB_VlwieaaLm887ckdaZygTmLra7SBBpnpxng6NvfRUBRHgb8dtq5_EgrHsueLvbjDRy5DxQF7ITrYiYWJe_KCQhnK3p6Pq-PN92rulKn8N22u8
     rooms: a1d2d05c-c76b-48d3-9019-1d25da6a4997
     config:
      health:
        data: |
          SEND_MSTEAMS="YES"
          MSTEAMS_WEBHOOK_URL="https://ikelte.webhook.office.com/webhookb2/78fb5c89-26e1-4242-91e1-de43c34dd0c3@0133bb48-f790-4560-a64d-ac46a472fbbc/IncomingWebhook/CHANNEL/cfdc2d13-bff2-4780-9e2d-713e4a8a2c0f"
          DEFAULT_RECIPIENT_MSTEAMS="2cc989e3854c4c9dac06d659c34cd279"

  
   child:
   claiming:
     enabled: true
     token: LTQRyk26vZmK7sNH9LsHF4PMqB_VlwieaaLm887ckdaZygTmLra7SBBpnpxng6NvfRUBRHgb8dtq5_EgrHsueLvbjDRy5DxQF7ITrYiYWJe_KCQhnK3p6Pq-PN92rulKn8N22u8
     rooms: a1d2d05c-c76b-48d3-9019-1d25da6a4997
#  --set parent.claiming.enabled="true" --set parent.claiming.token="LTQRyk26vZmK7sNH9LsHF4PMqB_VlwieaaLm887ckdaZygTmLra7SBBpnpxng6NvfRUBRHgb8dtq5_EgrHsueLvbjDRy5DxQF7ITrYiYWJe_KCQhnK3p6Pq-PN92rulKn8N22u8" --set parent.claiming.rooms="a1d2d05c-c76b-48d3-9019-1d25da6a4997" --set child.claiming.enabled=true --set child.claiming.token="LTQRyk26vZmK7sNH9LsHF4PMqB_VlwieaaLm887ckdaZygTmLra7SBBpnpxng6NvfRUBRHgb8dtq5_EgrHsueLvbjDRy5DxQF7ITrYiYWJe_KCQhnK3p6Pq-PN92rulKn8N22u8" --set child.claiming.rooms="a1d2d05c-c76b-48d3-9019-1d25da6a4997"
