apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: default
spec:
 chart:
   spec:
     chart: netdata
     sourceRef:
       kind: HelmRepository
       name: netdata
     version: ">=2.7.0"
 interval: 1m0s
